import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ClerkProvider } from "@clerk/nextjs";
import { viVN, enUS } from "@clerk/localizations";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "%s | Floral Shop",
    absolute: "Floral Shop",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const localization = locale === "vi" ? viVN : enUS;

  return (
    <NextIntlClientProvider messages={messages}>
      <ClerkProvider
        localization={localization}
        appearance={{
          variables: {
            colorPrimary: "#e11d48",
          },
        }}
      >
        <html lang={locale}>
          <body className={`${inter.className}  antialiased`}>{children}</body>
        </html>
      </ClerkProvider>
    </NextIntlClientProvider>
  );
}
